# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Om föreningen
    url: om-foreningen-och-styrelsen
    weight: 10
  - name: Bli medlem
    url: bli-medlem
    weight: 20
  - name: Kalender
    url: kalender
    weight: 30
  - name: Västerbottens Turf-klassiker
    url: vasterbottens-turf-klassiker
    weight: 40
  - name: Vandringspokalen
    url: vandringspokal
    weight: 50
  - name: Profilkläder
    url: profilklader
    weight: 60
  - name: Vad är Turf?
    url: publication
    weight: 70
  - name: Kontakt
    url: contact
    weight: 80
  - name: Turfgame.com
    url: https://turfgame.com/
    weight: 90
